name: Python Workload Executor
description: "Sets up Python, installs dependencies, and runs a benchmark script."

inputs:
  python_version:
    description: "Python version to use (e.g. 3.10)."
    required: true
  script_path:
    description: "Path to the benchmark script, relative to the repo root."
    required: true
  project_path:
    description: "Path to the project directory, relative to repo root."
    required: false
    default: "."
  extras:
    description: "Base comma-separated list of extras."
    required: false
    default: ""
  extras_hw:
    description: "Comma-separated list of hardware-specific extras. This list is appended to extras."
    required: false
    default: ""
  runtime_flags:
    description: "Base runtime flags to pass to the benchmark script."
    required: false
    default: ""
  runtime_flags_hw:
    description: "Hardware-specific runtime flags, appended to runtime_flags."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # ratchet:actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project_path }}
        EXTRAS: ${{ inputs.extras }}
        EXTRAS_HW: ${{ inputs.extras_hw }}
      run: |
        echo "::group::Install dependencies"
        "$GITHUB_ACTION_PATH/install_deps.sh"
        echo "::endgroup::"

    - name: Run benchmark script
      shell: bash
      env:
        SCRIPT: ${{ inputs.script_path }}
        ARGS: "${{ inputs.runtime_flags }} ${{ inputs.runtime_flags_hw }}"
      run: |
        echo "::group::Run Benchmark Script"

        set -euo pipefail
        export PYTHONPATH="$GITHUB_WORKSPACE/user_repo"
        cd "$GITHUB_WORKSPACE/user_repo" || exit 1

        echo "SCRIPT: $SCRIPT"
        echo "ARGS: $ARGS"
        python "$SCRIPT" $ARGS

        echo "::endgroup::"
