# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Python Workload Executor
description: "Sets up Python, installs dependencies, and runs a benchmark script."

inputs:
  python_version:
    description: "Python version to use (e.g. 3.10)."
    required: true
  script_path:
    description: "Path to the benchmark script, relative to the repo root."
    required: true
  project_path:
    description: "Path to the project directory, relative to repo root."
    required: false
    default: "."
  extras:
    description: "Base comma-separated list of extras."
    required: false
    default: ""
  extras_hw:
    description: "Comma-separated list of hardware-specific extras. This list is appended to extras."
    required: false
    default: ""
  runtime_flags:
    description: "Base runtime flags to pass to the benchmark script."
    required: false
    default: ""
  runtime_flags_hw:
    description: "Hardware-specific runtime flags, appended to runtime_flags."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install Python
      shell: bash
      env: 
        PYTHON_VERSION: ${{ inputs.python_version }}
      run: |
        echo "::group::Install Python"
        "$GITHUB_ACTION_PATH/setup_python.sh" "$PYTHON_VERSION"
        echo "::endgroup::"

    - name: Install dependencies
      shell: bash
      env:
        PROJECT_PATH: ${{ inputs.project_path }}
        EXTRAS: ${{ inputs.extras }}
        EXTRAS_HW: ${{ inputs.extras_hw }}
      run: |
        echo "::group::Install dependencies"
        "$GITHUB_ACTION_PATH/install_deps.sh"
        echo "::endgroup::"

    - name: Run benchmark script
      shell: bash
      working-directory: user_repo
      env:
        SCRIPT: ${{ inputs.script_path }}
        ARGS: "${{ inputs.runtime_flags }} ${{ inputs.runtime_flags_hw }}"
      run: |
        echo "::group::Run benchmark script"
        export PYTHONPATH="$GITHUB_WORKSPACE/user_repo"
        echo "SCRIPT: $SCRIPT | ARGS: $ARGS"
        python "$SCRIPT" $ARGS
        echo "::endgroup::"
